### ISSUE TITLE
Problem with emulator TN5250J 0.7.6 version.

### ISSUE THREAD

**Issue by Fux007** [tn5250j/tn5250j.github.io#8]
Good evening ,
Problem with emulator TN5250J 0.7.6 version.
I wanted to point the sequent problem . In emulation if the choice and placed on the 24 line, the cursor is always positioned on the 23 and not going on 24. I'm talking about a screen with only one choice you should always give a tab to make her position . In the previous version this problem was not there.
You can somehow help me?
thanks in advance for your kind reply
![tn5250j](https://cloud.githubusercontent.com/assets/22883586/19431766/1a418110-945a-11e6-95ee-d387f613f996.jpg)

**Comment by duncan3dc** [comment]
Hi @Fux007, thanks for your detailed issue, but this repository is for the TN5250J website, could you please log your issue here instead: https://github.com/tn5250j/tn5250j/issues/new

Sorry for the confusion
